import type { Metadata } from "next"

import { geistMono, geistSans } from '@/config/fonts'
import { Providers } from '@/shared/presentation/components'
import "./globals.css"


export const metadata: Metadata = {
  title: {
    default: "Next Template",
    template: "%s | Next Template",
  },
  description: "Generated by Next Template",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
